export const experiences = [
  {
    title: "SVT/PV Software Systems Engineer",
    company: "Ciena",
    companyLink: "https://www.ciena.com/",
    duration: "Jul 2025 — Present",
    location: "Hybrid, Delhi",
    techStack: [
      "Postman",
      "Playwright",
      "Javascript",
      "Testrail",
      "Jira",
      "Newman",
      "Teamcity",
    ],
  },
  {
    title: "SDET Intern",
    company: "Ciena",
    companyLink: "https://www.ciena.com/",
    duration: "Jan 2025 — Jun 2025",
    location: "Hybrid, Delhi",
    techStack: [
      "Postman",
      "Playwright",
      "Javascript",
      "Testrail",
      "Jira",
      "Newman",
    ],
  },
  {
    title: "Co-founder",
    company: "Thinkspace",
    companyLink: "https://thinkspacedel.in",
    duration: "Jun 2026 — Present",
    location: "Delhi",
    techStack: ["React", "Supabase", "Netlify", "Tailwind"],
  },
  {
    title: "Full-Stack Trainee",
    company: "D2I Technology",
    companyLink: "https://www.sustainable-discipleship.com/",
    duration: "May 2024 — Jul 2024",
    location: "Remote",
    techStack: ["React", "MySQL", "Knex.js", "Material UI"],
  },
  {
    title: "Active Volunteer",
    company: "ALiAS — Amity Linux Assistance Sapience",
    companyLink: "https://asetalias.in/",
    duration: "2022 — 2024",
    location: "Delhi",
    techStack: [],
  },
  {
    title: "Participant",
    company: "Supabase Week X Hackathon",
    companyLink: "https://supabase.com/blog/supabase-hackathon-lwx",
    duration: "Dec 2023",
    location: "Remote",

    techStack: ["React", "Tailwind", "Pinecone", "Bun", "DaisyUI", "Supabase"],
  },
  {
    title: "Participant",
    company: "HackTheMountains 2.0 Hackathon",
    companyLink: "https://hackthemountains2.devfolio.co/",
    duration: "Sep 2022",
    location: "Remote",
    techStack: [
      "Raspberry Pi 4",
      "Vue.js",
      "MongoDB",
      "Tailwind CSS",
      "Twilio API",
      "OpenWeather API",
    ],
  },
];
